let a = document.getElementById("a");
let b = document.getElementById("b");
let c = document.getElementById("c");
let d = document.getElementById("d");
let e = document.getElementById("e");
let f = document.getElementById("f");
let g = document.getElementById("g");
let h = document.getElementById("h");
let i = document.getElementById("i");
let j = document.getElementById("j");
let k = document.getElementById("k");
let l = document.getElementById("l");
let m = document.getElementById("m");
let n = document.getElementById("n");
let o = document.getElementById("o");
let p = document.getElementById("p");
let q = document.getElementById("q");
let r = document.getElementById("r");
let s = document.getElementById("s");
let t = document.getElementById("t");
let u = document.getElementById("u");
let v = document.getElementById("v");
let w = document.getElementById("w");
let x = document.getElementById("x");
let y = document.getElementById("y");
let z = document.getElementById("z");
let ae = document.getElementById("ä");
let oe = document.getElementById("ö");
let ue = document.getElementById("ü");
let ss = document.getElementById("ß");

let buttons = [a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, ae, oe, ue, ss];

export default buttons;